# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17_g3DTgM1kXbuvsPO77ImOFWk9_W_f6q
"""

import pandas as pd

# Load the datasets
oms_df = pd.read_csv("/content/oms.csv")
pf_df = pd.read_csv("/content/pf.csv")

# Ensure the key columns exist
if "SKU" not in oms_df.columns or "awbno" not in oms_df.columns:
    raise ValueError("Missing 'sku' or 'awbno' columns in oms.csv")
if "SKU" not in pf_df.columns or "awbno" not in pf_df.columns:
    raise ValueError("Missing 'sku' or 'awbno' columns in pf.csv")

oms_df['SKU'] = oms_df['SKU'].astype(str)
pf_df['SKU'] = pf_df['SKU'].astype(str)

merged_df = pd.merge(oms_df, pf_df, on=["SKU", "awbno"], how="outer", indicator=True)

# Create 'final inventory status' column
def determine_status(row):
    if row["_merge"] == "both":
        return row["getStatus"]  # Match found
    elif row["_merge"] == "right_only":
        return "missing"  # awbno not found in oms.csv
    elif row["_merge"] == "left_only":
        return f"{row['getStatus']}-sku-mismatch" if pd.notna(row["getStatus"]) else "sku-mismatch"

merged_df["final inventory status"] = merged_df.apply(determine_status, axis=1)

import os

# Create the 'outputs' directory if it doesn't exist
os.makedirs("outputs", exist_ok=True)

# Save to CSV
merged_df.to_csv("outputs/merged_data.csv", index=False)

from google.colab import files
files.download("/content/outputs/merged_data.csv")